[package]
name = "tlc_common"
version = "0.0.1"
authors = ["Mark Boss <mark.boss@uni-tuebingen.de>"]
edition = "2018"


[lib]
name = "tlc_common"

[dependencies]
num = "0.4.0"
image = "0.24.3"
imageproc = "0.23.0"
rexif = "0.7.3"
nalgebra = "0.31.1"
log = "0.4.11"